version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./services/backup/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prog_app
    restart: always
    ports:
      - "15000:5432"
  backend:
    build:
      context: ./services
      dockerfile: Dockerfile
      target: prod
    container_name: ts-node-docker
    restart: always
    ports:
      - '40000:8080'
    command: npm run docker-run
